routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\GenreController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnimemovieController;
use App\Http\Controllers\Admin\AnimeserieController;
use App\Http\Controllers\Open\AnimemovieOpenController;
use App\Http\Controllers\Open\AnimeserieOpenController;
use App\Http\Controllers\Admin\SeasonController;
use App\Http\Controllers\Open\QuestionOpenController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie/{animeserie}/show', [AnimeserieOpenController::class, 'show'])
    ->name('open.animeserie.show');
Route::resource('/open/animeserie', AnimeserieOpenController::class);

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('open.animeserie.index');
Route::resource('/open/animeserie', AnimeserieOpenController::class);


Route::get('/animemovie', [AnimemovieOpenController::class, 'index'])
    ->name('open.animemovie.index');
Route::resource('/open/animemovie', AnimemovieOpenController::class);

Route::get('/animemovie/{animemovie}/show', [AnimemovieOpenController::class, 'show'])
    ->name('open.animemovie.show');
Route::resource('/open/animemovie', AnimemovieOpenController::class);



// Auth main
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('admin/user/{user}/delete', [UserController::class, 'delete'])
        ->name('user.delete');
    Route::resource('/admin/user', UserController::class);

    Route::get('admin/genre/{genre}/delete', [GenreController::class, 'delete'])
        ->name('genre.delete');
    Route::resource('/admin/genre', GenreController::class);

    Route::get('admin/seasons/{season}/delete', [SeasonController::class, 'delete'])
        ->name('seasons.delete');
    Route::resource('/admin/seasons', SeasonController::class);

    Route::get('admin/animemovie/{animemovie}/delete', [AnimemovieController::class, 'delete'])
        ->name('animemovie.delete');
    Route::resource('/admin/animemovie', AnimemovieController::class);

    Route::get('/admin/animeserie/{animeserie}/delete', [AnimeserieController::class, 'delete'])
        ->name('animeserie.delete');
    Route::resource('/admin/animeserie', AnimeserieController::class);
});

// Auth Question
Route::group(['middleware' => ['role:admin|user']], function () {
    Route::get('admin/question/{question}/delete', [QuestionController::class, 'delete'])
        ->name('question.delete');
    Route::resource('/admin/question', QuestionController::class);

    Route::get('request/anime', [QuestionOpenController::class, 'create'])
    ->name('open.question.create');
    Route::resource('/admin/question', QuestionController::class);
});
require __DIR__ . '/auth.php';

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    use HasFactory;

    protected $fillable = ['genrename'];

    public function question()
    {
        return $this->hasMany(Question::class);
    }

    public function animeserie()
    {
        return $this->hasMany(Animeserie::class);
    }

    public function animemovie()
    {
        return $this->hasMany(Animemovie::class);
    }
}

app/Http/Controllers/Admin/GenreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\GenreStoreRequest;
use App\Http\Requests\GenreUpdateRequest;
use App\Models\Genre;
use Illuminate\Http\Request;
use Throwable;

class GenreController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:index genre', ['only' => ['index']]);
        $this->middleware('permission:show genre', ['only' => ['show']]);
        $this->middleware('permission:create genre', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit genre', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete genre', ['only' => ['delete', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $genres = Genre::all();

        return view('admin.genre.index', compact('genres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.genre.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GenreStoreRequest $request)
    {
        $genre = new Genre();
        $genre->genrename = $request->genrename;
        $genre->save();

        return redirect()->route('genre.index')->with('status', 'Succesfully added new Genre!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function show(Genre $genre)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function edit(Genre $genre)
    {
        return view('admin.genre.edit', compact('genre'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function update(GenreUpdateRequest $request, Genre $genre)
    {
        $genre->genrename = $request->genrename;
        $genre->save();

        return redirect()->route('genre.index')->with('status', 'Succesfully updated this Genre!');
    }

    public function delete(Genre $genre)
    {
        return view('admin.genre.delete', compact('genre'));   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function destroy(Genre $genre)
    {
        try {
            $genre->delete();
        } catch (Throwable $error)
        {
            report($error);
            return redirect()->route('genre.index')->with('status-wrong', 'This genre is in use!
            Make sure it is not in use.');
        }

        return redirect()->route('genre.index')->with('status', 'This genre was deleted succesfully!');
    }
}

resources/views/admin/genre/create.blade.php
@extends ('layouts.layout')

@section('content')
@if ($errors->any())
<div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
    <ul class="mt-3 list-disc list-inside text-sn text-red-600">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
    <form action="{{route('genre.store')}}" method="POST">
        @csrf
        <div class="flex flex-col mb-5">
            <!-- Genrename -->
            <label for="genrename" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Genrename</label>
            <input type="text" required id="genrename" name="genrename" placeholder="Enter Genrename" value="{{ old('genrename')}}" 
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 text-gray-600 placeholder-gray-400
                            rounded-md @error('genrename') border-red-500 @enderror outline-none">
        </div>

        <!-- Buttons -->
        <div class="text-right">
            <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Add</button>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('genre.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/genre/delete.blade.php
@extends ('layouts.layout')

@section('content')
<div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
    <form action="{{ route('genre.destroy', ['genre' => $genre->id]) }}" method="POST">
        @method('DELETE')
        @csrf
        <div class="flex flex-col mb-5">
            <!-- Genrename -->
            <label for="genrename" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Genrename</label>
            <input type="text" disabled id="genrename" name="genrename" value="{{ $genre->genrename }}" 
                            class="flex-1 py-2 border-b-2 border-gray-400 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md
                            outline-none cursor-not-allowed">
            </div>

        <!-- Buttons -->
        <div class="text-right">
            <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Delete</button>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('genre.index')}}" class="mr-8 text-sm text-red-600 font-bold">Abort</a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/genre/edit.blade.php
@extends ('layouts.layout')

@section('content')
@if ($errors->any())
<div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
    <ul class="mt-3 list-disc list-inside text-sn text-red-600">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
    <form action="{{route('genre.update', ['genre' => $genre->id]) }}" method="POST">
        @method('PUT')
        @csrf
        <!-- Genrename -->
        <div class="flex flex-col mb-5">
            <label for="genrename" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Genrename</label>
            <input type="text" required id="genrename" name="genrename" placeholder="Enter genrename" value="{{ old('genrename', $genre->genrename)}}" 
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 text-gray-600 placeholder-gray-400 
                            rounded-md @error('genrename') border-red-500 @enderror
                            outline-none">
        </div>

        <!-- Buttons -->
        <div class="text-right">
            <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Edit</button>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('genre.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/genre/index.blade.php
@extends ('layouts.layout')

@section('content')
@if (session('status'))
<div class="bg-green-200 text-green-900 rouned-lg shadow-md p-6 pr-10 mb-8">
    {{ session('status') }}
</div>
@endif
@if (session('status-wrong'))
<div class="bg-red-200 text-red-900 rouned-lg shadow-md p-6 pr-10 mb-8">
    {{ session('status-wrong') }}
</div>
@endif

<h3 class="text-2xl font-semibold text-gray-700 dark:text-gray-200">Genre - Table</h3>

<div class="flex flex-col mt-8">
    <div class="my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200 dark:border-gray-800">
            <table class="w-full whitespace-no-wrap">
                <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="px-4 py-3">
                            ID
                        </th>
                        <th class="px-4 py-3">
                            Genrename
                        </th>
                        <th class="px-4 py-3">
                            Created_at
                        </th>
                        <th class="px-4 py-3">
                            Updated_at
                        </th>
                        <th class="px-4 py-3">
                            Edit
                        </th>
                        <th class="px-4 py-3">
                            Delete
                        </th>
                    </tr>
                </thead>

                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    @foreach($genres as $genre)
                    <tr class="text-gray-700 dark:text-gray-400">
                        <!-- ID -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$genre->id}}
                                </p>
                            </div>
                        </td>
                        <!-- Genrename -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$genre->genrename}}
                                </p>
                            </div>
                        </td>
                        <!-- Created at -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$genre->created_at}}
                                </p>
                            </div>
                        </td>
                        <!-- Updated at -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$genre->updated_at}}
                                </p>
                            </div>
                        </td>
                        <!-- Edit -->
                        <td class="px-4 py-3 text-sm">
                            <a href="{{ route('genre.edit', ['genre' => $genre->id]) }}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                        <!-- Delete -->
                        <td class="px-4 py-3 text-sm">
                            <a href="{{ route('genre.delete', ['genre' => $genre->id]) }}" class="text-indigo-600 hover:text-indigo-900">Delete</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('genre.create')}}" class="mr-4 text-orange-600 hover:text-orange-900 font-bold">Add +</a>
        </div>
    </div>
</div>
@endsection