routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\GenreController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnimemovieController;
use App\Http\Controllers\Admin\AnimeserieController;
use App\Http\Controllers\Open\AnimemovieOpenController;
use App\Http\Controllers\Open\AnimeserieOpenController;
use App\Http\Controllers\Admin\SeasonController;
use App\Http\Controllers\Open\QuestionOpenController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie/{animeserie}/show', [AnimeserieOpenController::class, 'show'])
    ->name('open.animeserie.show');
Route::resource('/open/animeserie', AnimeserieOpenController::class);

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('open.animeserie.index');
Route::resource('/open/animeserie', AnimeserieOpenController::class);


Route::get('/animemovie', [AnimemovieOpenController::class, 'index'])
    ->name('open.animemovie.index');
Route::resource('/open/animemovie', AnimemovieOpenController::class);

Route::get('/animemovie/{animemovie}/show', [AnimemovieOpenController::class, 'show'])
    ->name('open.animemovie.show');
Route::resource('/open/animemovie', AnimemovieOpenController::class);



// Auth main
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('admin/user/{user}/delete', [UserController::class, 'delete'])
        ->name('user.delete');
    Route::resource('/admin/user', UserController::class);

    Route::get('admin/genre/{genre}/delete', [GenreController::class, 'delete'])
        ->name('genre.delete');
    Route::resource('/admin/genre', GenreController::class);

    Route::get('admin/seasons/{season}/delete', [SeasonController::class, 'delete'])
        ->name('seasons.delete');
    Route::resource('/admin/seasons', SeasonController::class);

    Route::get('admin/animemovie/{animemovie}/delete', [AnimemovieController::class, 'delete'])
        ->name('animemovie.delete');
    Route::resource('/admin/animemovie', AnimemovieController::class);

    Route::get('/admin/animeserie/{animeserie}/delete', [AnimeserieController::class, 'delete'])
        ->name('animeserie.delete');
    Route::resource('/admin/animeserie', AnimeserieController::class);
});

// Auth Question
Route::group(['middleware' => ['role:admin|user']], function () {
    Route::get('admin/question/{question}/delete', [QuestionController::class, 'delete'])
        ->name('question.delete');
    Route::resource('/admin/question', QuestionController::class);

    Route::get('request/anime', [QuestionOpenController::class, 'create'])
    ->name('open.question.create');
    Route::resource('/admin/question', QuestionController::class);
});
require __DIR__ . '/auth.php';

app/Models/Season.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Season extends Model
{
    use HasFactory;

    public function animeserie()
    {
        return $this->hasMany(Animeserie::class);
    }
}

app/Http/Controllers/Admin/SeasonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\SeasonStoreRequest;
use App\Http\Requests\SeasonUpdateRequest;
use App\Models\Season;
use Illuminate\Http\Request;
use Throwable;

class SeasonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get seasons
        $seasons = Season::all();

        //return a view with $seasons
        return view('admin.seasons.index', compact('seasons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.seasons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SeasonStoreRequest $request)
    {
        //seasonname from the create goes to database
        $season = new Season();
        $season->seasonname = $request->seasonname;
        $season->save();

        //when succesful, return to index with status message
        return redirect()->route('seasons.index')->with('status', 'Succesfully added new Season!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Season  $season
     * @return \Illuminate\Http\Response
     */
    public function show(Season $season)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Season  $season
     * @return \Illuminate\Http\Response
     */
    public function edit(Season $season)
    {
        return view('admin.seasons.edit', compact('season'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Season  $season
     * @return \Illuminate\Http\Response
     */
    public function update(SeasonUpdateRequest $request, Season $season)
    {
        $season->seasonname = $request->seasonname;
        $season->save();

        return redirect()->route('seasons.index')->with('status', 'Succesfully updated this Season!');
    }

    public function delete(Season $season)
    {
        return view('admin.seasons.delete', compact('season'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Season  $season
     * @return \Illuminate\Http\Response
     */
    public function destroy(Season $season)
    {
        try {
            $season->delete();
        } catch (Throwable $error)
        {
            report($error);
            return redirect()->route('seasons.index')->with('status-wrong', 'This season is in use!
            Make sure it is not in use.');
        }

        return redirect()->route('seasons.index')->with('status', 'This season was deleted succesfully!');
    }
}

resources/views/admin/seasons/create.blade.php
@extends ('layouts.layout')

@section('content')
    @if ($errors->any())
        <div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
            <ul class="mt-3 list-disc list-inside text-sn text-red-600">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
        <form action="{{route('seasons.store')}}" method="POST">
            @csrf
            <!-- Name input -->
            <div class="flex flex-col mb-5">
                <label for="seasonname" class="inline-block w-30 mr-6 text-left
                                    font-bold text-gray-600">Season</label>
                <input type="text" required id="seasonname" name="seasonname" placeholder="Enter Seasonname" value="{{ old('seasonname') }}"
                    class="flex-1 py-2 border-b-2 focus:border-indigo-600
                            text-gray-600 placeholder-gray-400 rounded-md @error('seasonname') border-red-500 @enderror
                            outline-none">
            </div>

            <div class="text-right">
                <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Add</button>
            </div>
            <div class="text-right mt-2">
                <a href="{{route('seasons.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/seasons/delete.blade.php
@extends ('layouts.layout')

@section('content')
    <div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
        <form action="{{ route('seasons.destroy', ['season' => $season->id]) }}" method="POST">
            @method('DELETE')
            @csrf
            <!-- Name input -->
            <div class="flex flex-col mb-5">
                <label for="seasonname" class="inline-block w-30 mr-6 text-left
                                    font-bold text-gray-600">Season</label>
                <input type="text" disabled id="seasonname" name="seasonname" placeholder="Seasonname" value="{{ $season->seasonname }}"
                    class="flex-1 py-2 border-b-2 border-gray-400 focus:border-indigo-600
                            text-gray-600 placeholder-gray-400 rounded-md
                            outline-none">
            </div>

            <div class="text-right">
                <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Delete</button>
            </div>
            <div class="text-right mt-2">
                <a href="{{route('seasons.index')}}" class="mr-8 text-sm text-red-600 font-bold">Abort</a>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/seasons/edit.blade.php
@extends ('layouts.layout')

@section('content')
    @if ($errors->any())
        <div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
            <ul class="mt-3 list-disc list-inside text-sn text-red-600">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
        <form action="{{route('seasons.update', ['season' => $season->id]) }}" method="POST">
            @method('PUT')
            @csrf
            <!-- Name input -->
            <div class="flex flex-col mb-5">
                <label for="Seasonname" class="inline-block w-30 mr-6 text-left
                                    font-bold text-gray-600">Season</label>
                <input type="text" required id="seasonname" name="seasonname" placeholder="Seasonname" value="{{ old('seasonname', $season->seasonname)}}"
                    class="flex-1 py-2 border-b-2 focus:border-indigo-600
                            text-gray-600 placeholder-gray-400 rounded-md @error('seasonname') border-red-500 @enderror
                            outline-none">
            </div>

            <div class="text-right">
                <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Edit</button>
            </div>
            <div class="text-right mt-2">
                <a href="{{route('seasons.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/seasons/index.blade.php
@extends ('layouts.layout')

@section('content')
    @if (session('status'))
        <div class="bg-green-200 text-green-900 rouned-lg shadow-md p-6 pr-10 mb-8">
            {{ session('status') }}
        </div>
    @endif
    @if (session('status-wrong'))
        <div class="bg-red-200 text-red-900 rouned-lg shadow-md p-6 pr-10 mb-8">
            {{ session('status-wrong') }}
        </div>
    @endif

    <h3 class="text-gray-700 text-3xl font-medium">Seasons - Table</h3>

    <div class="flex flex-col mt-8">
        <div class="my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
            <div
                class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200 dark:border-gray-800">
                <table class="w-full whitespace-no-wrap">
                    <thead>
                        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                            <th
                                class="px-4 py-3">
                                ID
                            </th>
                            <th
                                class="px-4 py-3">
                                Seasonname
                            </th>
                            <th
                                class="px-4 py-3">
                                Created_at
                            </th>
                            <th
                                class="px-4 py-3">
                                Updated_at
                            </th>
                            <th
                                class="px-4 py-3">
                                Edit
                            </th>
                            <th class="px-4 py-3">
                                Delete
                            </th>
                        </tr>
                    </thead>

                    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                        @foreach($seasons as $season)
                        <tr class="text-gray-700 dark:text-gray-400">
                            <!-- ID -->
                            <td class="px-4 py-3">
                                <div class="flex items-center text-sm">
                                    <p class="font-semibold">
                                        {{$season->id}}
                                    </p>
                                </div>
                            </td>
                            <!-- Name -->
                            <td class="px-4 py-3">
                                <div class="flex items-center text-sm">
                                    <p class="font-semibold">
                                        {{$season->seasonname}}
                                    </p>
                                </div>
                            </td>
                            <!-- Created at -->
                            <td class="px-4 py-3">
                                <div class="flex items-center text-sm">
                                    <p class="font-semibold">
                                        {{$season->created_at}}
                                    </p>
                                </div>
                            </td>
                            <!-- Updated at -->
                            <td class="px-4 py-3">
                                <div class="flex items-center text-sm">
                                    <p class="font-semibold">
                                        {{$season->updated_at}}
                                    </p>
                                </div>
                            </td>
                            <!-- Edit -->
                            <td class="px-4 py-3 text-sm">
                                <a href="{{ route('seasons.edit', ['season' => $season->id]) }}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                            <!-- Delete -->
                            <td class="px-4 py-3 text-sm">
                                <a href="{{ route('seasons.delete', ['season' => $season->id]) }}" class="text-indigo-600 hover:text-indigo-900">Delete</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="text-right mt-2">
                <a href="{{ route('seasons.create') }}" class="mr-4 text-orange-600 hover:text-orange-900 font-bold">Add +</a>
            </div>
        </div>
    </div>
@endsection