routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\GenreController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnimemovieController;
use App\Http\Controllers\Admin\AnimeserieController;
use App\Http\Controllers\Open\AnimemovieOpenController;
use App\Http\Controllers\Open\AnimeserieOpenController;
use App\Http\Controllers\Admin\SeasonController;
use App\Http\Controllers\Open\QuestionOpenController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie/{animeserie}/show', [AnimeserieOpenController::class, 'show'])
    ->name('open.animeserie.show');
Route::resource('/open/animeserie', AnimeserieOpenController::class);

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('open.animeserie.index');
Route::resource('/open/animeserie', AnimeserieOpenController::class);


Route::get('/animemovie', [AnimemovieOpenController::class, 'index'])
    ->name('open.animemovie.index');
Route::resource('/open/animemovie', AnimemovieOpenController::class);

Route::get('/animemovie/{animemovie}/show', [AnimemovieOpenController::class, 'show'])
    ->name('open.animemovie.show');
Route::resource('/open/animemovie', AnimemovieOpenController::class);



// Auth main
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('admin/user/{user}/delete', [UserController::class, 'delete'])
        ->name('user.delete');
    Route::resource('/admin/user', UserController::class);

    Route::get('admin/genre/{genre}/delete', [GenreController::class, 'delete'])
        ->name('genre.delete');
    Route::resource('/admin/genre', GenreController::class);

    Route::get('admin/seasons/{season}/delete', [SeasonController::class, 'delete'])
        ->name('seasons.delete');
    Route::resource('/admin/seasons', SeasonController::class);

    Route::get('admin/animemovie/{animemovie}/delete', [AnimemovieController::class, 'delete'])
        ->name('animemovie.delete');
    Route::resource('/admin/animemovie', AnimemovieController::class);

    Route::get('/admin/animeserie/{animeserie}/delete', [AnimeserieController::class, 'delete'])
        ->name('animeserie.delete');
    Route::resource('/admin/animeserie', AnimeserieController::class);
});

// Auth Question
Route::group(['middleware' => ['role:admin|user']], function () {
    Route::get('admin/question/{question}/delete', [QuestionController::class, 'delete'])
        ->name('question.delete');
    Route::resource('/admin/question', QuestionController::class);

    Route::get('request/anime', [QuestionOpenController::class, 'create'])
    ->name('open.question.create');
    Route::resource('/admin/question', QuestionController::class);
});
require __DIR__ . '/auth.php';

app/Models/AnimeMovie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Animemovie extends Model
{
    use HasFactory;

    protected $fillable = [
        'moviename',
        'summary',
        'releasedate'
    ];

    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }
}

app/Http/Controllers/Admin/AnimemovieController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Animemovie;
use App\Http\Requests\AnimemovieStoreRequest;
use App\Http\Requests\AnimemovieUpdateRequest;
use App\Models\Genre;
use Carbon\Carbon;
use Illuminate\Http\Request;

class AnimemovieController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:index animemovie', ['only' => ['index']]);
        $this->middleware('permission:show animemovie', ['only' => ['show']]);
        $this->middleware('permission:create animemovie', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit animemovie', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete animemovie', ['only' => ['delete', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Animemovie $animemovies)
    {
        $animemovies = Animemovie::with('genre')->get();

        return view('admin.animemovie.index', compact('animemovies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $animemovies = Animemovie::with('genre')->get();
        $genres = Genre::with('animemovie')->get();

        return view('admin.animemovie.create', compact('animemovies', 'genres'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AnimemovieStoreRequest $request)
    {
        $animemovie = new Animemovie();
        $animemovie->moviename = $request->moviename;
        $animemovie->summary = $request->summary;
        $animemovie->releasedate = $request->releasedate;
        $animemovie->genre_id = $request->genre_id;
        $animemovie->updated_at = Carbon::now();
        $animemovie->save();

        return redirect()->route('animemovie.index')->with('status', 'Succesfully added a new Animemovie!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Animemovie  $animemovie
     * @return \Illuminate\Http\Response
     */
    public function show(Animemovie $animemovie)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Animemovie  $animemovie
     * @return \Illuminate\Http\Response
     */
    public function edit(Animemovie $animemovie)
    {
        $genres = Genre::with('animemovie')->get();


        return view('admin.animemovie.edit', compact('animemovie', 'genres'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Animemovie  $animemovie
     * @return \Illuminate\Http\Response
     */
    public function update(AnimemovieUpdateRequest $request, Animemovie $animemovie)
    {
        $animemovie->moviename = $request->moviename;
        $animemovie->summary = $request->summary;
        $animemovie->genre_id = $request->genre_id;
        $animemovie->releasedate = $request->releasedate;
        $animemovie->save();

        return redirect()->route('animemovie.index')->with('status', 'Succesfully updated this Animemovie!');
    }

    public function delete(Animemovie $animemovie)
    {
        return view('admin.animemovie.delete', compact('animemovie'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Animemovie  $animemovie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Animemovie $animemovie)
    {
        $animemovie->delete();

        return redirect()->route('animemovie.index')->with('status', 'This Animemovie was deleted succesfully!');
    }
}

resources/views/admin/animemovie/create.blade.php
@extends ('layouts.layout')

@section('content')
@if ($errors->any())
<div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
    <ul class="mt-3 list-disc list-inside text-sn text-red-600">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
    <form action="{{route('animemovie.store')}}" method="POST">
        @csrf
        <!-- Name input -->
        <div class="flex flex-col mb-5">
            <label for="moviename" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Animemovie</label>
            <input type="text" required id="moviename" name="moviename" placeholder="Enter Moviename" value="{{ old('moviename')}}" class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('moviename') border-red-500 @enderror
                            outline-none">
        </div>
        <!-- summary input -->
        <div class="flex flex-col mb-5">
            <label for="summary" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Summary</label>
            <input type="text" required id="summary" name="summary" placeholder="Enter Summary" value="{{ old('summary')}}" class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('summary') border-red-500 @enderror
                            outline-none">
        </div>

        <!-- releasedate input -->
        <div class="flex flex-col mb-5">
            <label for="releasedate" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Releasedate</label>
            <input type="number" required id="releasedate" name="releasedate" placeholder="Enter Releasedate" value="{{ old('releasedate')}}" class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('releasedate') border-red-500 @enderror
                            outline-none">
        </div>        
        
        <!-- Genre input -->
        <div class="flex flex-col mb-5">
            <label for="genrename" class="inline-block w-30 mr-6 text-left font-bold text-gray-600">Genrename</label>
            <select type="text" required id="genrename" name="genre_id" class="flex-1 py-2 border-b-2 focus:border-indigo-600 text-gray-600 placeholder-gray-400 rounded-md outline-none">
                @foreach ($genres as $genre)
                <option value="{{$genre->id}}">{{$genre->genrename}}</option>
                @endforeach
            </select>
        </div>      
        

        <div class="text-right">
            <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Add</button>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('animemovie.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/animemovie/delete.blade.php
@extends ('layouts.layout')

@section('content')
<div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
    <form action="{{ route('animemovie.destroy', ['animemovie' => $animemovie->id]) }}" method="POST">
        @method('DELETE')
        @csrf
        <!-- Name input -->
        <div class="flex flex-col mb-5">
            <label for="moviename" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Animemovie</label>
            <input type="text" disabled id="moviename" name="moviename" placeholder="Moviename" value="{{ $animemovie->moviename }}" class="flex-1 py-2 border-b-2 border-gray-400 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md
                            outline-none">
        </div>

        <div class="text-right">
            <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Delete</button>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('animemovie.index')}}" class="mr-8 text-sm text-red-600 font-bold">Abort</a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/animemovie/edit.blade.php
@extends ('layouts.layout')

@section('content')
@if ($errors->any())
<div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
    <ul class="mt-3 list-disc list-inside text-sn text-red-600">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
    <form action="{{route('animemovie.update', ['animemovie' => $animemovie->id]) }}" method="POST">
        @method('PUT')
        @csrf
        <!-- Name input -->
        <div class="flex flex-col mb-5">
            <label for="moviename" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Animemovie</label>
            <input type="text" required id="moviename" name="moviename" placeholder="Moviename" value="{{ old('moviename', $animemovie->moviename)}}" class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('moviename') border-red-500 @enderror
                            outline-none">
        </div>

        <!-- Summary input -->
        <div class="flex flex-col mb-5">
            <label for="summary" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Summary</label>
            <input type="text" required id="summary" name="summary" placeholder="Summary" value="{{ old('summary', $animemovie->summary)}}" class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('summary') border-red-500 @enderror
                            outline-none">
        </div>

        <!-- Releasedate input -->
        <div class="flex flex-col mb-5">
            <label for="releasedate" class="inline-block w-30 mr-6 text-left 
                                    font-bold text-gray-600">Releasedate</label>
            <input type="number" required id="releasedate" name="releasedate" placeholder="Releasedate" value="{{ old('releasedate', $animemovie->releasedate)}}" class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('releasedate') border-red-500 @enderror
                            outline-none">
        </div>        

        <!-- Genre input -->
        <div class="flex flex-col mb-5">
            <label for="genrename" class="inline-block w-30 mr-6 text-left font-bold text-gray-600">Genrename</label>
            <select type="text" required id="genrename" name="genre_id" class="flex-1 py-2 border-b-2 focus:border-indigo-600 text-gray-600 placeholder-gray-400 rounded-md outline-none">
                @foreach ($genres as $genre)
                <option value="{{$genre->id}}">{{$genre->genrename}}</option>
                @endforeach
            </select>
        </div>     

        <div class="text-right">
            <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Edit</button>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('animemovie.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/animemovie/index.blade.php
@extends ('layouts.layout')

@section('content')
@if (session('status'))
<div class="bg-green-200 text-green-900 rouned-lg shadow-md p-6 pr-10 mb-8">
    {{ session('status') }}
</div>
@endif

<h3 class="text-2xl font-semibold text-gray-700 dark:text-gray-200">Animemovies - Table</h3>

<div class="flex flex-col mt-8">
    <div class="my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200 dark:border-gray-800">
            <table class="w-full">
                <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="px-4 py-3">
                            ID
                        </th>
                        <th class="px-4 py-3">
                            Moviename
                        </th>
                        <th class="px-4 py-3">
                            Summary
                        </th>
                        <th class="px-4 py-3">
                            Releasedate
                        </th>
                        <th class="px-4 py-3">
                            Genre
                        </th>
                        <th class="px-4 py-3">
                            Created_at
                        </th>
                        <th class="px-4 py-3">
                            Updated_at
                        </th>
                        <th class="px-4 py-3">
                            Edit
                        </th>
                        <th class="px-4 py-3">
                            Delete
                        </th>
                    </tr>
                </thead>

                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    @foreach($animemovies as $animemovie)
                    <tr class="text-gray-700 dark:text-gray-400">
                        <!-- ID -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->id}}
                                </p>
                            </div>
                        </td>
                        <!-- Name -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->moviename}}
                                </p>
                            </div>
                        </td>
                        <!-- Summary -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->summary}}
                                </p>
                            </div>
                        </td>
                        <!-- Releasedate -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->releasedate}}
                                </p>
                            </div>
                        </td>
                        <!-- Genre -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->genre->genrename}}
                                </p>
                            </div>
                        </td>
                        <!-- Created at -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->created_at}}
                                </p>
                            </div>
                        </td>
                        <!-- Updated at -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animemovie->updated_at}}
                                </p>
                            </div>
                        </td>
                        <!-- Edit -->
                        <td class="px-4 py-3 text-sm">
                            <a href="{{ route('animemovie.edit', ['animemovie' => $animemovie->id]) }}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                            <!-- Delete -->
                        <td class="px-4 py-3 text-sm">
                            <a href="{{ route('animemovie.delete', ['animemovie' => $animemovie->id]) }}" class="text-indigo-600 hover:text-indigo-900">Delete</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('animemovie.create')}}" class="mr-4 text-orange-600 hover:text-orange-900 font-bold">Add +</a>
        </div>
    </div>
</div>
@endsection