routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\GenreController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnimemovieController;
use App\Http\Controllers\Admin\AnimeserieController;
use App\Http\Controllers\Open\AnimemovieOpenController;
use App\Http\Controllers\Open\AnimeserieOpenController;
use App\Http\Controllers\Admin\SeasonController;
use App\Http\Controllers\Open\QuestionOpenController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('animeserie.index');

Route::get('/animeserie/{animeserie}/show', [AnimeserieOpenController::class, 'show'])
    ->name('open.animeserie.show');
Route::resource('/open/animeserie', AnimeserieOpenController::class);

Route::get('/animeserie', [AnimeserieOpenController::class, 'index'])
    ->name('open.animeserie.index');
Route::resource('/open/animeserie', AnimeserieOpenController::class);


Route::get('/animemovie', [AnimemovieOpenController::class, 'index'])
    ->name('open.animemovie.index');
Route::resource('/open/animemovie', AnimemovieOpenController::class);

Route::get('/animemovie/{animemovie}/show', [AnimemovieOpenController::class, 'show'])
    ->name('open.animemovie.show');
Route::resource('/open/animemovie', AnimemovieOpenController::class);



// Auth main
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('admin/user/{user}/delete', [UserController::class, 'delete'])
        ->name('user.delete');
    Route::resource('/admin/user', UserController::class);

    Route::get('admin/genre/{genre}/delete', [GenreController::class, 'delete'])
        ->name('genre.delete');
    Route::resource('/admin/genre', GenreController::class);

    Route::get('admin/seasons/{season}/delete', [SeasonController::class, 'delete'])
        ->name('seasons.delete');
    Route::resource('/admin/seasons', SeasonController::class);

    Route::get('admin/animemovie/{animemovie}/delete', [AnimemovieController::class, 'delete'])
        ->name('animemovie.delete');
    Route::resource('/admin/animemovie', AnimemovieController::class);

    Route::get('/admin/animeserie/{animeserie}/delete', [AnimeserieController::class, 'delete'])
        ->name('animeserie.delete');
    Route::resource('/admin/animeserie', AnimeserieController::class);
});

// Auth Question
Route::group(['middleware' => ['role:admin|user']], function () {
    Route::get('admin/question/{question}/delete', [QuestionController::class, 'delete'])
        ->name('question.delete');
    Route::resource('/admin/question', QuestionController::class);

    Route::get('request/anime', [QuestionOpenController::class, 'create'])
    ->name('open.question.create');
    Route::resource('/admin/question', QuestionController::class);
});
require __DIR__ . '/auth.php';

app/Models/AnimeSerie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Animeserie extends Model
{
    use HasFactory;

    protected $fillable = ['seriename', 'summary', 'releasedate'];

    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }

    public function season()
    {
        return $this->belongsTo(Season::class);
    }
}

app/Http/Controllers/Admin/AnimeSerieController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AnimeserieStoreRequest;
use App\Http\Requests\AnimeserieUpdateRequest;
use App\Models\Animeserie;
use App\Models\Genre;
use App\Models\Season;
use Illuminate\Http\Request;

class AnimeserieController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:index animeserie', ['only' => ['index']]);
        $this->middleware('permission:show animeserie', ['only' => ['show']]);
        $this->middleware('permission:create animeserie', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit animeserie', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete animeserie', ['only' => ['delete', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $animeseries = Animeserie::with('genre', 'season')->get();

        return view('admin.animeserie.index', compact('animeseries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $animeseries = Animeserie::with('genre')->get();
        $genres = Genre::with('animeserie')->get();
        $seasons = Season::with('animeserie')->get();

        return view('admin.animeserie.create', compact('animeseries', 'genres', 'seasons'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AnimeserieStoreRequest $request)
    {
        $animeserie = new Animeserie();
        $animeserie->seriename = $request->seriename;
        $animeserie->season_id = $request->season_id;
        $animeserie->summary = $request->summary;
        $animeserie->genre_id = $request->genre_id;
        $animeserie->releasedate = $request->releasedate;
        $animeserie->save();

        return redirect()->route('animeserie.index')->with('status', 'Succesfully added new Anime!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Animeserie  $animeserie
     * @return \Illuminate\Http\Response
     */
    public function show(Animeserie $animeserie)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Animeserie  $animeserie
     * @return \Illuminate\Http\Response
     */
    public function edit(Animeserie $animeserie)
    {
        $genres = Genre::with('animeserie')->get();
        $seasons = Season::with('animeserie')->get();

        return view('admin.animeserie.edit', compact('animeserie', 'genres', 'seasons'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Animeserie  $animeserie
     * @return \Illuminate\Http\Response
     */
    public function update(AnimeserieUpdateRequest $request, Animeserie $animeserie)
    {
        $animeserie->seriename = $request->seriename;
        $animeserie->season_id = $request->season_id;
        $animeserie->summary = $request->summary;
        $animeserie->genre_id = $request->genre_id;
        $animeserie->releasedate = $request->releasedate;
        $animeserie->save();

        return redirect()->route('animeserie.index')->with('status', 'Succesfully updated this Anime!');
    }

    public function delete(Animeserie $animeserie)
    {
        return view('admin.animeserie.delete', compact('animeserie'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Animeserie  $animeserie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Animeserie $animeserie)
    {
        $animeserie->delete();

        return redirect()->route('animeserie.index')->with('status', 'This Anime was deleted succesfully!');
    }
}

resources/views/admin/animeserie/create.blade.php
@extends ('layouts.layout')

@section('content')
    @if ($errors->any())
        <div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
            <ul class="mt-3 list-disc list-inside text-sn text-red-600">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
        <form action="{{route('animeserie.store')}}" method="POST">
            @csrf
            <div class="flex flex-col mb-5">
                <!-- Seriename -->
                <label for="seriename" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Animeserie</label>
                <input type="text" required id="seriename" name="seriename" placeholder="Enter Animeserie" value="{{ old('seriename')}}"
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('seriename') border-red-500 @enderror
                            outline-none mb-2">

                <!-- Seasonname -->
                <label for="seasonname" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Seasonname</label>
                <select type="text" required id="seasonname" name="season_id"  
                        class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                        text-gray-600 placeholder-gray-400 rounded-md outline-none mb-2">
                    @foreach ($seasons as $season)
                        <option value="{{$season->id}}">{{$season->seasonname}}</option>
                    @endforeach
                </select>

                <!-- Summary -->
                <label for="summary" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Summary</label>
                <textarea required id="summary" name="summary" placeholder="Add summary" value="{{ old('summary')}}"
                            class="py-2 border focus:border-indigo-600 
                            text-gray-600 rounded-md placeholder-gray-400 @error('summary') border-red-500 @enderror
                            outline-none mb-2"></textarea>

                <!-- Genrename -->
                <label for="genrename" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Genrename</label>
                <select type="text" required id="genrename" name="genre_id"
                        class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                        text-gray-600 placeholder-gray-400 rounded-md outline-none mb-2">
                    @foreach ($genres as $genre)
                        <option value="{{$genre->id}}">{{$genre->genrename}}</option>
                    @endforeach
                </select>

                <!-- Releasedate -->
                <div class="custom-number-input h-auto w-32">
                    <label for="releasedate" class="inline-block w-30 mr-6 text-left 
                        font-bold text-gray-600">Releasedate(Year)</label>
                    <div class="flex flex-row h-10 w-full rounded-lg relative bg-transparent mt-1">
                        <input type="number" class="outline-none rounded focus:outline-none text-center w-full bg-gray-300 font-semibold
                        text-md hover:text-black focus:text-black  md:text-basecursor-default flex items-center text-gray-700"
                        id="releasedate" name="releasedate" value="0">
                    </div>     
                </div>
                
                <!-- Buttons -->
                <div class="text-right">
                    <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Add</button> 
                </div>
                <div class="text-right mt-2">
                    <a href="{{route('animeserie.index')}}" class="mr-6 text-sm text-red-600 font-bold">Abort</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/animeserie/delete.blade.php
@extends ('layouts.layout')

@section('content')
    <div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
        <form action="{{ route('animeserie.destroy', ['animeserie' => $animeserie->id]) }}" method="POST">
            @method('DELETE')
            @csrf
            <div class="flex flex-col mb-5">
                <!-- Seriename -->
                <label for="seriename" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Animeserie</label>
                <input type="text" disabled id="seriename" name="seriename" value="{{$animeserie->seriename}}"
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('seriename') border-red-500 @enderror
                            outline-none mb-2 cursor-not-allowed">

                <!-- Seasonname -->
                <label for="seasonname" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Seasonname</label>
                <input type="text" disabled id="seasonname" name="seasonname" value="{{$animeserie->season->seasonname}}"
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('seasonname') border-red-500 @enderror
                            outline-none mb-2 cursor-not-allowed">

                <!-- Summary -->
                <label for="summary" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Summary</label>
                <textarea disabled id="summary" name="summary"
                            class="py-2 border focus:border-indigo-600 
                            text-gray-600 rounded-md placeholder-gray-400 @error('summary') border-red-500 @enderror
                            outline-none mb-2 cursor-not-allowed">{{$animeserie->summary}}</textarea>

                <!-- Seriename -->
                <label for="genrename" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Genrename</label>
                <input type="text" disabled id="genrename" name="genrename" value="{{$animeserie->genre->genrename}}"
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('genrename') border-red-500 @enderror
                            outline-none mb-2 cursor-not-allowed">

                <!-- Releasedate -->
                <div class="custom-number-input h-auto w-32">
                    <label for="releasedate" class="inline-block w-30 mr-6 text-left 
                        font-bold text-gray-600">Releasedate(Year)</label>
                    <div class="flex flex-row h-10 w-full rounded-lg relative bg-transparent mt-1">
                        <input type="number" disabled class="outline-none rounded focus:outline-none text-center w-full bg-gray-300 font-semibold
                         text-md hover:text-black focus:text-black  md:text-basecursor-default flex items-center text-gray-700 cursor-not-allowed" 
                         id="releasedate" name="releasedate" value="{{$animeserie->releasedate}}">
                    </div>     
                </div>
    
                <!-- Buttons -->
                <div class="text-right">
                    <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Delete</button> 
                </div>
                <div class="text-right mt-2">
                    <a href="{{route('animeserie.index')}}" class="mr-8 text-sm text-red-600 font-bold">Abort</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/animeserie/edit.blade.php
@extends ('layouts.layout')

@section('content')
    @if ($errors->any())
        <div class="bg-red-200 text-red-900 rounded-lg shadow-md p-6 pr-10 mb-8 ">
            <ul class="mt-3 list-disc list-inside text-sn text-red-600">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="bg-white p-10 md:w-3/4 lg:w-1/2 mx-auto rounded-md">
        <form action="{{ route('animeserie.update', ['animeserie' => $animeserie->id]) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="flex flex-col mb-5">
                <!-- Seriename -->
                <label for="seriename" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Animeserie</label>
                <input type="text" required id="seriename" name="seriename" placeholder="Enter Animeserie" value="{{ old('animeserie', $animeserie->seriename)}}"
                            class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                            text-gray-600 placeholder-gray-400 rounded-md @error('seriename') border-red-500 @enderror
                            outline-none mb-2">

                <!-- Seasonname -->
                <label for="seasonname" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Seasonname</label>
                <select type="text" required id="seasonname" name="season_id"
                        class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                        text-gray-600 placeholder-gray-400 rounded-md outline-none mb-2">
                    @foreach ($seasons as $season)
                        <option value="{{$season->id}}">{{$season->seasonname}}</option>
                    @endforeach
                </select>

                <!-- Summary -->
                <label for="summary" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Summary</label>
                <textarea id="summary" required name="summary" placeholder="Add summary"
                            class="py-2 border focus:border-indigo-600 
                            text-gray-600 rounded-md placeholder-gray-400 @error('summary') border-red-500 @enderror
                            outline-none mb-2">{{$animeserie->summary}}</textarea>

                <!-- Genrename -->
                <label for="genrename" class="inline-block w-30 mr-6 text-left 
                            font-bold text-gray-600">Genrename</label>
                <select type="text" required id="genrename" name="genre_id"
                        class="flex-1 py-2 border-b-2 focus:border-indigo-600 
                        text-gray-600 placeholder-gray-400 rounded-md outline-none mb-2">
                    @foreach ($genres as $genre)
                        <option value="{{$genre->id}}">{{$genre->genrename}}</option>
                    @endforeach
                </select>

                <!-- Releasedate -->
                <div class="custom-number-input h-auto w-32">
                    <label for="releasedate" class="inline-block w-30 mr-6 text-left 
                        font-bold text-gray-600">Releasedate(Year)</label>
                    <div class="flex flex-row h-10 w-full rounded-lg relative bg-transparent mt-1">
                        <input type="number" required class="outline-none rounded focus:outline-none text-center w-full bg-gray-300 font-semibold
                         text-md hover:text-black focus:text-black  md:text-basecursor-default flex items-center text-gray-700" 
                         id="releasedate" name="releasedate" value="{{ old('animeserie', $animeserie->releasedate)}}">
                    </div>     
                </div>

                <!-- Buttons -->
                <div class="text-right">
                    <button class="py-3 px-8 bg-indigo-600 text-white font-bold rounded-md">Edit</button>
                </div>
                <div class="text-right mt-2">
                    <a href="{{route('animeserie.index')}}" class="mr-8 text-sm text-red-600 font-bold">Abort</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/animeserie/index.blade.php
@extends ('layouts.layout')

@section('content')
@if (session('status'))
<div class="bg-green-200 text-green-900 rouned-lg shadow-md p-6 pr-10 mb-8">
    {{ session('status') }}
</div>
@endif

<h3 class="text-2xl font-semibold text-gray-700 dark:text-gray-200">Animeseries - Table</h3>

<div class="flex flex-col mt-8">
    <div class="my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200 dark:border-gray-800">
            <table class="w-full">
                <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="px-4 py-3">
                            ID
                        </th>
                        <th class="px-4 py-3">
                            Seriename
                        </th>
                        <th class="px-4 py-3">
                            Season
                        </th>
                        <th class="px-4 py-3">
                            Summary
                        </th>
                        <th class="px-4 py-3">
                            Genrename
                        </th>
                        <th class="px-4 py-3">
                            Releasedate
                        </th>
                        <th class="px-4 py-3">
                            Created_at
                        </th>
                        <th class="px-4 py-3">
                            Updated_at
                        </th>
                        <th class="px-4 py-3">
                            Edit
                        </th>
                        <th class="px-4 py-3">
                            Delete
                        </th>
                    </tr>
                </thead>

                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    @foreach($animeseries as $animeserie)
                    <tr class="text-gray-700 dark:text-gray-400">
                        <!-- ID -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->id}}
                                </p>
                            </div>
                        </td>
                        <!-- Seriename -->
                        <td class="px-4 py-3 whitespace-no-wrap">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->seriename}}
                                </p>
                            </div>
                        </td>
                        <!-- Seasonname -->
                        <td class="px-4 py-3 whitespace-no-wrap">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->season->seasonname}}
                                </p>
                            </div>
                        </td>
                        <!-- Summary -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->summary}}
                                </p>
                            </div>
                        </td>
                        <!-- Genrename -->
                        <td class="px-4 py-3 whitespace-no-wrap">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->genre->genrename}}
                                </p>
                            </div>
                        </td>
                        <!-- Releasedate -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->releasedate}}
                                </p>
                            </div>
                        </td>
                        <!-- Created at -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->created_at}}
                                </p>
                            </div>
                        </td>
                        <!-- Updated at -->
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <p class="font-semibold">
                                    {{$animeserie->updated_at}}
                                </p>
                            </div>
                        </td>
                        <!-- Edit -->
                        <td class="px-4 py-3 text-sm">
                            <a href="{{ route('animeserie.edit', ['animeserie' => $animeserie->id]) }}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                        <!-- Delete -->
                        <td class="px-4 py-3 text-sm">
                            <a href="{{ route('animeserie.delete', ['animeserie' => $animeserie->id]) }}" class="text-indigo-600 hover:text-indigo-900">Delete</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="text-right mt-2">
            <a href="{{route('animeserie.create')}}" class="mr-4 text-orange-600 hover:text-orange-900 font-bold">Add +</a>
        </div>
    </div>
</div>
@endsection